line-length = 100
src = ["src", "management", "tests"]
target-version = "py314"

[lint]
select = ["ALL"]
extend-select = [
    "DOC201",
    "DOC402",
    "DOC502",
    "RUF100",
]
preview = true
explicit-preview-rules = true
unfixable = ["T201"]
ignore = [
    "D100",
    "D104",
    "D103",
    "D101",
    "ANN401",
    "E501",
    "TC002",
    "TC006",
    "D107",
    "D102",
    "TC001",
    "TC003",
    "D106",
    "D105",
    "EXE002",
    "FIX002",
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401",  # Module imported but unused
]
"**/migrations/**" = [
    "ANN201",  # Missing return type annotation for public function
    "ANN001",  # Missing type annotation for function argument
    "ARG001",  # Unused function argument"
    "RUF012",  # Mutable class attributes
]
"**/models.py" = [
    "RUF012",
]
"**/factories.py" = [
    "PLR0913",
]
"tests/**" = [
    "S101",  # Use of assert detected
    "PT003",
    "ARG001",
    "ARG002",
    "PLR2004",
    "PLR0913",
]

[lint.isort]
combine-as-imports = true
known-first-party = ["modern_python_template"]

[lint.ruff]
strictly-empty-init-modules = true

[lint.pylint]
max-args = 4
max-bool-expr = 3
max-branches = 8
max-locals = 10
max-nested-blocks = 3
max-positional-args = 3
max-statements = 30

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[lint.pep8-naming]
classmethod-decorators = [
    "pydantic.validator",
    "pydantic.field_validator",
]

[lint.flake8-pytest-style]
fixture-parentheses = true
mark-parentheses = false

[lint.pydocstyle]
convention = "google"
property-decorators = ["pydantic.computed_field"]
