services:
  api:
    volumes:
      - ../src:/app/src:ro
    command:
      - uvicorn
      - fastdjango.entrypoints.fastapi.app:app
      - --reload
      - --host
      - 0.0.0.0
      - --port
      - "8000"

  celery-worker:
    volumes:
      - ../src:/app/src:ro
    command:
      - watchmedo
      - auto-restart
      - --directory=/app/src
      - --pattern=*.py
      - --recursive
      - --
      - celery
      - --app=fastdjango.entrypoints.celery.app
      - worker
      - --loglevel=${LOGGING_LEVEL:-INFO}
      - --concurrency=2

  celery-beat:
    volumes:
      - ../src:/app/src:ro
    command:
      - watchmedo
      - auto-restart
      - --directory=/app/src
      - --pattern=*.py
      - --recursive
      - --
      - celery
      - --app=fastdjango.entrypoints.celery.app
      - beat
      - --loglevel=${LOGGING_LEVEL:-INFO}

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"

  minio:
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
